# Action Cable configuration

# Async adapter only works within the same process.
# Suitable for development and single-process production.
development:
  adapter: async

# Test adapter for running tests.
test:
  adapter: test

# Using async adapter for production.
# Solid Cable disabled to avoid multiple database requirement.
production:
  adapter: async