import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateHealthReport = (user, readings, medications) => {
  // Create new PDF document
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 102, 204);
  doc.text('Diabetes Health Report', 105, 20, { align: 'center' });
  
  // Patient info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Patient: ${user.name}`, 20, 40);
  doc.text(`Email: ${user.email}`, 20, 48);
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, 56);
  
  // HbA1c Summary
  doc.setFontSize(14);
  doc.setTextColor(0, 102, 204);
  doc.text('HbA1c Summary', 20, 75);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  
  const latestReading = readings.length > 0 ? readings[0].value : 'No data';
  const targetValue = 7.0;
  
  doc.text(`Latest HbA1c: ${latestReading}%`, 30, 85);
  doc.text(`Target: ${targetValue}%`, 30, 93);
  
  // Status color indicator
  let status = 'Normal';
  let statusColor = [0, 128, 0]; // Green
  
  if (latestReading !== 'No data') {
    if (latestReading >= 7 && latestReading < 8) {
      status = 'Warning';
      statusColor = [255, 165, 0]; // Orange
    } else if (latestReading >= 8) {
      status = 'High';
      statusColor = [255, 0, 0]; // Red
    }
  }
  
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.text(`Status: ${status}`, 30, 101);
  
  // Readings Table
  doc.setTextColor(0, 102, 204);
  doc.text('Recent Readings', 20, 120);
  
  if (readings.length > 0) {
    const tableData = readings.slice(0, 10).map(r => [
      new Date(r.date).toLocaleDateString(),
      r.value + '%',
      r.notes || '-'
    ]);
    
    autoTable(doc, {
      startY: 125,
      head: [['Date', 'HbA1c Value', 'Notes']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [0, 102, 204] }
    });
  } else {
    doc.setTextColor(0, 0, 0);
    doc.text('No readings available', 30, 130);
  }
  
  // Medications
  const finalY = doc.lastAutoTable?.finalY || 150;
  
  doc.setTextColor(0, 102, 204);
  doc.text('Current Medications', 20, finalY + 15);
  
  if (medications.length > 0) {
    const medData = medications.map(m => [
      m.name,
      m.dosage,
      m.frequency,
      new Date(m.start_date).toLocaleDateString()
    ]);
    
    autoTable(doc, {
      startY: finalY + 20,
      head: [['Medication', 'Dosage', 'Frequency', 'Started']],
      body: medData,
      theme: 'striped',
      headStyles: { fillColor: [0, 102, 204] }
    });
  } else {
    doc.setTextColor(0, 0, 0);
    doc.text('No medications added', 30, finalY + 25);
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(
      `Generated by Diabetes Tracker App - Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }
  
  // Save the PDF
  doc.save(`diabetes-report-${new Date().toISOString().split('T')[0]}.pdf`);
};
